Handle more websocket api for futures
adshao/go-binance pull request #209
Opened 2021-01-26 17:07 UTC by dohki

1. Handle and test user data stream api for futures
2. Validate and support levels and rate in some api for futures

2021-01-26 17:08 UTC, dohki commented
This PR is based on the #175, but only implements for futures

2021-01-31 01:50 UTC, adshao requested changes

2021-01-31 01:50 UTC, adshao commented on v2/futures/websocket_service.go
> +func WsMarkPriceServe(symbol string, rate time.Duration, handler WsMarkPriceHandler, errHandler ErrHandler) (doneC, stopC chan struct{}, err error) {
This change will break backward compatibility of this API, I would suggest adding a new method, i.e. `WsMarkPriceServeWithRate`.

2021-02-12 12:39 UTC, adshao approved these changes

2021-02-12 12:39 UTC, merged