Order Rate Limit
adshao/go-binance pull request #320
Opened 2021-11-02 15:01 UTC by amaioli

It's a first tentative version to manage rate limit info from Binance. In this version I've extended the Order Response structure including 10s and 1m order trade limit from header response.

2021-11-03 14:33 UTC, adshao requested changes

2021-11-05 07:26 UTC, amaioli commented on v2/futures/client.go
> +	err = json.Unmarshal(data, &t)
ok let me change the codes adding a return. In that case we've to modify all the others functions but it's more clean

2021-11-10 15:33 UTC, amaioli commented
Hi adshao, did you have the chance to check the changes?

2021-11-10 17:10 UTC, adshao approved these changes

2021-11-10 17:11 UTC, adshao commented
> Hi adshao, did you have the chance to check the changes?

Yes, I'm reviewing this pr, sorry for the late reply.
Thanks for the contribution! @amaioli

2021-11-10 17:11 UTC, merged