impl GetAllCoinsInfoService
adshao/go-binance pull request #328
Opened 2021-11-17 08:12 UTC by qct

Implement of get all coins information: 
GET /sapi/v1/capital/config/getall (HMAC SHA256)

response:
```
[
    {
        "coin": "BTC",
        "depositAllEnable": true,
        "free": "0.08074558",
        "freeze": "0.00000000",
        "ipoable": "0.00000000",
        "ipoing": "0.00000000",
        "isLegalMoney": false,
        "locked": "0.00000000",
        "name": "Bitcoin",
        "networkList": [
            {
                "addressRegex": "^(bnb1)[0-9a-z]{38}$",
                "coin": "BTC",
                "depositDesc": "Wallet Maintenance, Deposit Suspended", // 仅在充值关闭时返回
                "depositEnable": false,
                "isDefault": false,        
                "memoRegex": "^[0-9A-Za-z\\-_]{1,120}$",
                "minConfirm": 1,  // 上账所需的最小确认数
                "name": "BEP2",
                "network": "BNB",            
                "resetAddressStatus": false,
                "specialTips": "Both a MEMO and an Address are required to successfully deposit your BEP2-BTCB tokens to Binance.",
                "unLockConfirm": 0,  // 解锁需要的确认数 
                "withdrawDesc": "Wallet Maintenance, Withdrawal Suspended", // 仅在提现关闭时返回
                "withdrawEnable": false,
                "withdrawFee": "0.00000220",
                "withdrawIntegerMultiple": "0.00000001",
                "withdrawMax": "9999999999.99999999",
                "withdrawMin": "0.00000440",
                "sameAddress": true  // 是否需要memo
            },
            {
                "addressRegex": "^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$|^(bc1)[0-9A-Za-z]{39,59}$",
                "coin": "BTC",
                "depositEnable": true,
                "isDefault": true,
                "memoRegex": "",
                "minConfirm": 1,  // 上账所需的最小确认数
                "name": "BTC",
                "network": "BTC",
                "resetAddressStatus": false,
                "specialTips": "",
                "unLockConfirm": 0,  // 解锁需要的确认数
                "withdrawEnable": true,
                "withdrawFee": "0.00050000",
                "withdrawIntegerMultiple": "0.00000001",
                "withdrawMax": "750",
                "withdrawMin": "0.00100000",
                "sameAddress": false
            }
        ],
        "storage": "0.00000000",
        "trading": true,
        "withdrawAllEnable": true,
        "withdrawing": "0.00000000"
    }
]
```

2021-11-17 15:43 UTC, adshao requested changes

2021-11-17 15:43 UTC, adshao commented on v2/asset_detail_service.go
> +func (s *GetAllCoinsInfoService) Do(ctx context.Context) (res []CoinInfo, err error) {
```suggestion
func (s *GetAllCoinsInfoService) Do(ctx context.Context) (res []*CoinInfo, err error) {
```
Use pointer here to keep consistent with other services.

2021-11-24 15:46 UTC, adshao requested changes

2021-11-24 15:46 UTC, adshao commented on v2/asset_detail_service.go
> +	data, err := s.c.callAPI(ctx, r)
```
        data, err := s.c.callAPI(ctx, r, opts...)
	if err != nil {
		return []*CoinInfo{}, err
	}
	res = make([]*CoinInfo, 0)
	err = json.Unmarshal(data, &res)
	if err != nil {
		return []*CoinInfo{}, err
	}
	return res, nil
```

2021-12-16 15:10 UTC, adshao commented
Hi @qct , could you please run this test check on https://github.com/adshao/go-binance/blob/master/.travis.yml, there are gofmt/golint issues on your code.

2022-01-26 10:51 UTC, MJ23M commented
Hi, @adshao can you merge this pull request into master?

2022-01-29 03:14 UTC, qct commented
@adshao sorry for the late, seems someone has done the job, close this pr.

2022-01-29 03:14 UTC, closed without merging

2022-11-14 11:38 UTC, byroncoetsee commented
Is there documentation for this anywhere?