Add NOTIONAL filter support
adshao/go-binance pull request #481
Opened 2023-04-15 16:03 UTC by mm2175

I found some symbols filter have changned in binance, eg. for maticusdt, the following format is returned:

```json
        {
          "filterType": "NOTIONAL",
          "minNotional": "5.00000000",
          "applyMinToMarket": true,
          "maxNotional": "9000000.00000000",
          "applyMaxToMarket": false,
          "avgPriceMins": 5
        },
```

2023-04-22 13:38 UTC, adshao commented
Thanks for the update, could you please rebase master branch and update your code?

2023-04-25 02:44 UTC, mm2175 commented
> Thanks for the update, could you please rebase master branch and update your code?

Sure, already done this.

2023-04-27 03:08 UTC, adshao commented
Hi @mm2175 , could you please fix the vet error [here](https://github.com/adshao/go-binance/actions/runs/4793160600/jobs/8525360519?pr=481)

2023-04-27 11:49 UTC, mm2175 commented
@adshao fixed.

2023-05-03 14:46 UTC, adshao requested changes

2023-05-03 14:46 UTC, adshao commented on v2/futures/client.go
> +
Do not print message in a base client, use `c.debug` instead. However, I don't think this change is necessary.

2023-05-09 14:26 UTC, adshao approved these changes

2023-05-09 14:26 UTC, merged